version: "3.8"
services:
  server:
    ports:
      - 7256:80
      - 5172:5173
    restart: always
    build:
      context: docker
      dockerfile: server.Dockerfile
    volumes:
      - ./configuration/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/src
  
  db:
    ports:
      - 5431:5432
    restart: always
    build:
      context: docker
      dockerfile: db.Dockerfile
    env_file:
      - configuration/db.env
    volumes:
      - .:/docker-entrypoint-initdb.d
  
  app:
    restart: always
    build:
      context: docker
      dockerfile: app.Dockerfile
    env_file:
      - configuration/xdebug.env
    volumes:
      - ./src:/var/www/src
      - ./configuration/php.ini:/usr/local/etc/php/php.ini:ro
  
  composer:
    build:
      context: docker
      dockerfile: composer.Dockerfile
    volumes:
      - ./src:/var/www/src
  
  view:
    build:
      context: docker
      dockerfile: view.Dockerfile
    volumes:
      - ./src:/var/www/src
    
  artisan:
    build:
      context: docker
      dockerfile: app.Dockerfile
    volumes:
      - ./src:/var/www/src
    entrypoint: ["php", "/var/www/src/artisan"]